[2023-01-02T11:29:10.727+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: nba-dag.load scheduled__2023-01-01T11:29:00+00:00 [queued]>
[2023-01-02T11:29:10.744+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: nba-dag.load scheduled__2023-01-01T11:29:00+00:00 [queued]>
[2023-01-02T11:29:10.755+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-02T11:29:10.764+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2023-01-02T11:29:10.767+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-02T11:29:10.816+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load> on 2023-01-01 11:29:00+00:00
[2023-01-02T11:29:10.865+0000] {standard_task_runner.py:55} INFO - Started process 62 to run task
[2023-01-02T11:29:10.877+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'nba-dag', 'load', 'scheduled__2023-01-01T11:29:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/nba_dag.py', '--cfg-path', '/tmp/tmp9hsiz1nh']
[2023-01-02T11:29:10.879+0000] {standard_task_runner.py:83} INFO - Job 34: Subtask load
[2023-01-02T11:29:11.064+0000] {task_command.py:389} INFO - Running <TaskInstance: nba-dag.load scheduled__2023-01-01T11:29:00+00:00 [running]> on host 7b186f3dc822
[2023-01-02T11:29:11.165+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Javier Prieto
AIRFLOW_CTX_DAG_ID=nba-dag
AIRFLOW_CTX_TASK_ID=load
AIRFLOW_CTX_EXECUTION_DATE=2023-01-01T11:29:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-01T11:29:00+00:00
[2023-01-02T11:29:27.110+0000] {python.py:177} INFO - Done. Returned value was: PDF generated successfully
[2023-01-02T11:29:27.187+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=nba-dag, task_id=load, execution_date=20230101T112900, start_date=20230102T112910, end_date=20230102T112927
[2023-01-02T11:29:27.431+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2023-01-02T11:29:27.488+0000] {taskinstance.py:2582} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-01-02T11:32:07.087+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: nba-dag.load scheduled__2023-01-01T11:29:00+00:00 [queued]>
[2023-01-02T11:32:07.098+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: nba-dag.load scheduled__2023-01-01T11:29:00+00:00 [queued]>
[2023-01-02T11:32:07.099+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-02T11:32:07.100+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2023-01-02T11:32:07.102+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-02T11:32:07.120+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load> on 2023-01-01 11:29:00+00:00
[2023-01-02T11:32:07.132+0000] {standard_task_runner.py:55} INFO - Started process 80 to run task
[2023-01-02T11:32:07.139+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'nba-dag', 'load', 'scheduled__2023-01-01T11:29:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/nba_dag.py', '--cfg-path', '/tmp/tmpad4onxsl']
[2023-01-02T11:32:07.143+0000] {standard_task_runner.py:83} INFO - Job 39: Subtask load
[2023-01-02T11:32:07.233+0000] {task_command.py:389} INFO - Running <TaskInstance: nba-dag.load scheduled__2023-01-01T11:29:00+00:00 [running]> on host 7b186f3dc822
[2023-01-02T11:32:07.325+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Javier Prieto
AIRFLOW_CTX_DAG_ID=nba-dag
AIRFLOW_CTX_TASK_ID=load
AIRFLOW_CTX_EXECUTION_DATE=2023-01-01T11:29:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-01T11:29:00+00:00
[2023-01-02T11:32:14.473+0000] {local_task_job.py:82} ERROR - Received SIGTERM. Terminating subprocesses
[2023-01-02T11:32:14.828+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 80. PIDs of all processes in the group: [80]
[2023-01-02T11:32:14.864+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 80
[2023-01-02T11:32:14.910+0000] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-01-02T11:32:17.663+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/team_stats.py", line 541, in load
    open(f'data/logos/{team_logo}.png', 'wb').write(requests.get(f'https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/{team_id}.png&h=200&w=200').content)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/adapters.py", line 499, in send
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1485, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-01-02T11:32:19.058+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=nba-dag, task_id=load, execution_date=20230101T112900, start_date=20230102T113207, end_date=20230102T113218
[2023-01-02T11:32:19.838+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 39 for task load (Task received SIGTERM signal; 80)
[2023-01-02T11:32:20.296+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=80, status='terminated', exitcode=1, started='11:32:07') (80) terminated with exit code 1
[2023-01-02T11:32:20.334+0000] {local_task_job.py:159} INFO - Task exited with return code 143
[2023-01-02T11:32:20.631+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
