[2023-01-01T20:08:52.061+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: nba-dag.load manual__2023-01-01T20:08:31.042915+00:00 [queued]>
[2023-01-01T20:08:52.070+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: nba-dag.load manual__2023-01-01T20:08:31.042915+00:00 [queued]>
[2023-01-01T20:08:52.072+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-01T20:08:52.072+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2023-01-01T20:08:52.073+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-01T20:08:52.092+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load> on 2023-01-01 20:08:31.042915+00:00
[2023-01-01T20:08:52.120+0000] {standard_task_runner.py:55} INFO - Started process 70 to run task
[2023-01-01T20:08:52.133+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'nba-dag', 'load', 'manual__2023-01-01T20:08:31.042915+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/nba_dag.py', '--cfg-path', '/tmp/tmpux2wbnkt']
[2023-01-01T20:08:52.134+0000] {standard_task_runner.py:83} INFO - Job 14: Subtask load
[2023-01-01T20:08:52.331+0000] {task_command.py:389} INFO - Running <TaskInstance: nba-dag.load manual__2023-01-01T20:08:31.042915+00:00 [running]> on host 8bde35a245c7
[2023-01-01T20:08:52.468+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Javier Prieto
AIRFLOW_CTX_DAG_ID=nba-dag
AIRFLOW_CTX_TASK_ID=load
AIRFLOW_CTX_EXECUTION_DATE=2023-01-01T20:08:31.042915+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-01T20:08:31.042915+00:00
[2023-01-01T20:08:58.193+0000] {local_task_job.py:82} ERROR - Received SIGTERM. Terminating subprocesses
[2023-01-01T20:08:58.307+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 70. PIDs of all processes in the group: [70]
[2023-01-01T20:08:58.332+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 70
[2023-01-01T20:08:58.452+0000] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-01-01T20:08:58.701+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/team_stats.py", line 362, in load
    graphs()
  File "/opt/airflow/plugins/team_stats.py", line 196, in graphs
    player_stats = requests.get(f'https://api.sportsdata.io/v3/nba/stats/json/PlayerSeasonStats/2023?key={API_KEY}').json()
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/adapters.py", line 499, in send
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/connection.py", line 424, in connect
    tls_in_tls=tls_in_tls,
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 402, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir, ca_cert_data)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1485, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-01-01T20:08:58.826+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=nba-dag, task_id=load, execution_date=20230101T200831, start_date=20230101T200852, end_date=20230101T200858
[2023-01-01T20:09:01.689+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 14 for task load (Task received SIGTERM signal; 70)
[2023-01-01T20:09:04.530+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=70, status='terminated', exitcode=1, started='20:08:51') (70) terminated with exit code 1
[2023-01-01T20:09:04.575+0000] {local_task_job.py:159} INFO - Task exited with return code 143
[2023-01-01T20:09:04.833+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
